name = "Jlrs"
uuid = "29be08bc-e5fd-4da2-bbc1-72011c6ea2c9"
authors = ["Thomas van Doornmalen <thomas.vandoornmalen@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
